package net.superiorstate.ams.data.dao;

import jakarta.mail.*;
import jakarta.mail.internet.*;
import jakarta.persistence.EntityManager;
import jakarta.persistence.NoResultException;
import jakarta.persistence.Query;
import net.superiorstate.ams.data.util.EmailIdentity;
import net.superiorstate.ams.data.util.EmailTemplate;
import net.superiorstate.ams.model.activity.note.Email;
import net.superiorstate.ams.model.activity.note.EmailComparator;
import net.superiorstate.ams.model.general.PSP;
import net.superiorstate.ams.model.general.Person;
import net.superiorstate.ams.model.general.WebLink;
import net.superiorstate.ams.model.summit.archive.Employee;

import java.util.*;
import java.util.regex.Pattern;

public abstract class EmailDAO {

    /* ----------------------------- validation helpers ----------------------------- */

    public static boolean isValidEmail(String email) {
        if (email == null) return false;
        String regexPattern = "^(?=.{1,64}@)[A-Za-z0-9._%+-]+(\\.[A-Za-z0-9._%+-]+)*@"
                + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
        return Pattern.compile(regexPattern).matcher(email).matches();
    }

    private static InternetAddress[] toAddresses(Collection<String> emails) throws AddressException {
        if (emails == null || emails.isEmpty()) return new InternetAddress[0];
        List<String> cleaned = new ArrayList<>();
        for (String e : emails) {
            if (e == null) continue;
            String t = e.trim();
            if (t.isEmpty()) continue;
            if (!isValidEmail(t)) continue;
            cleaned.add(t);
        }
        if (cleaned.isEmpty()) return new InternetAddress[0];
        return InternetAddress.parse(String.join(", ", cleaned), true);
    }

    /* ----------------------------- public API (simple) ----------------------------- */

    public static void sendEmail(String fromWho, String toWho, String subject, String theMessage, EntityManager em)
            throws MessagingException {
        List<String> to = new ArrayList<>();
        if (toWho != null) to.add(toWho);
        sendEmail(fromWho, to, Collections.emptyList(), Collections.emptyList(), subject, theMessage, em);
    }

    public static void sendEmail(String fromWho, List<String> toWhoList, String subject, String theMessage, EntityManager em)
            throws MessagingException {
        sendEmail(fromWho, toWhoList, Collections.emptyList(), Collections.emptyList(), subject, theMessage, em);
    }

    /** Fully-specified variant (TO/CC/BCC). */
    public static void sendEmail(String fromWho,
                                 List<String> toWhoList,
                                 List<String> ccList,
                                 List<String> bccList,
                                 String subject,
                                 String htmlBody,
                                 EntityManager em) throws MessagingException {

        Session session = getSession(em);
        // Optional debug toggle via DB: SMTP_DEBUG = TRUE/FALSE
        try {
            String dbg = AppConstantDAO.getConstantValue(em, "SMTP_DEBUG");
            if (dbg != null && dbg.equalsIgnoreCase("true")) session.setDebug(true);
        } catch (Exception ignore) {}

        // FROM header (displayed) must be a verified sender in SMTP2GO
        String smtpFrom = safe(AppConstantDAO.getConstantValue(em, "SMTP_FROM"));
        if (smtpFrom.isBlank()) {
            // Try user email first
            if(isValidEmail(fromWho))
                smtpFrom = safe(fromWho);
                // fallback: SMTP_USER is often an email at SMTP2GO
            else
                smtpFrom = safe(AppConstantDAO.getConstantValue(em, "SMTP_USER"));
        }
        if (!isValidEmail(smtpFrom)) {
            throw new MessagingException("SMTP_FROM is not a valid/verified email address.");
        }

        MimeMessage msg = new MimeMessage(session);
        msg.setFrom(new InternetAddress(smtpFrom));

        // Reply-To: send replies to the human caller if provided
        if (isValidEmail(fromWho)) {
            msg.setReplyTo(new Address[]{new InternetAddress(fromWho.trim())});
        }

        // Recipients
        InternetAddress[] to = toAddresses(toWhoList);
        InternetAddress[] cc = toAddresses(ccList);
        InternetAddress[] bcc = toAddresses(bccList);

        if (to.length == 0 && cc.length == 0 && bcc.length == 0) {
            throw new MessagingException("No valid recipients (To/Cc/Bcc).");
        }
        if (to.length > 0)   msg.setRecipients(Message.RecipientType.TO, to);
        if (cc.length > 0)   msg.setRecipients(Message.RecipientType.CC, cc);
        if (bcc.length > 0)  msg.setRecipients(Message.RecipientType.BCC, bcc);

        msg.setSubject(safe(subject));

        // Multipart/alternative: plain text + HTML (improves spam score)
        MimeMultipart alternative = new MimeMultipart("alternative");

        // Plain text part (generated by stripping HTML)
        MimeBodyPart textPart = new MimeBodyPart();
        String plainText = stripHtml(htmlBody);
        textPart.setText(plainText, "utf-8", "plain");
        alternative.addBodyPart(textPart);

        // HTML part
        MimeBodyPart htmlPart = new MimeBodyPart();
        htmlPart.setContent(safe(htmlBody), "text/html; charset=utf-8");
        alternative.addBodyPart(htmlPart);

        msg.setContent(alternative);

        // V069: the explicit `mail.smtp.from` envelope override was removed here. SMTP2GO's
        // per-domain VERP owns the return-path (SPF alignment per verified sender domain);
        // forcing envelope-from = header From fought that alignment for verified domains.

        // Send using explicit Transport (honors timeouts)
        Transport transport = null;
        try {
            transport = session.getTransport("smtp");
            transport.connect(); // Authenticator in Session supplies creds
            transport.sendMessage(msg, msg.getAllRecipients());
        } finally {
            if (transport != null) try { transport.close(); } catch (MessagingException ignore) {}
        }
    }

    /* ----------------------------- public API (identity-aware, V069) ----------------------------- */

    /**
     * Identity-aware send (V069). The {@link EmailIdentity} fully specifies the
     * {@code From:} header (address + optional display name), {@code Reply-To:}, and
     * (optionally) the SMTP envelope sender. This is the path used by the resolver-wired
     * call sites; unlike the legacy {@code fromWho} overloads it does not derive From from
     * SMTP_FROM/recipient heuristics.
     *
     * @param identity resolved sender identity (must be non-null with a valid From address)
     */
    public static void sendEmail(EmailIdentity identity,
                                 List<String> toWhoList,
                                 List<String> ccList,
                                 List<String> bccList,
                                 String subject,
                                 String htmlBody,
                                 EntityManager em) throws MessagingException {

        if (identity == null || !isValidEmail(identity.fromAddress())) {
            throw new MessagingException("EmailIdentity is missing a valid From address.");
        }

        Session session = getSession(em);
        try {
            String dbg = AppConstantDAO.getConstantValue(em, "SMTP_DEBUG");
            if (dbg != null && dbg.equalsIgnoreCase("true")) session.setDebug(true);
        } catch (Exception ignore) {}

        MimeMessage msg = new MimeMessage(session);

        // From header, with optional friendly display name.
        try {
            if (identity.hasDisplayName()) {
                msg.setFrom(new InternetAddress(identity.fromAddress(), identity.displayName(), "UTF-8"));
            } else {
                msg.setFrom(new InternetAddress(identity.fromAddress()));
            }
        } catch (java.io.UnsupportedEncodingException e) {
            throw new MessagingException("Could not encode From display name.", e);
        }

        // Reply-To (sender's real inbox for human tiers).
        if (identity.hasReplyTo() && isValidEmail(identity.replyTo())) {
            msg.setReplyTo(new Address[]{new InternetAddress(identity.replyTo())});
        }

        InternetAddress[] to = toAddresses(toWhoList);
        InternetAddress[] cc = toAddresses(ccList);
        InternetAddress[] bcc = toAddresses(bccList);
        if (to.length == 0 && cc.length == 0 && bcc.length == 0) {
            throw new MessagingException("No valid recipients (To/Cc/Bcc).");
        }
        if (to.length > 0)  msg.setRecipients(Message.RecipientType.TO, to);
        if (cc.length > 0)  msg.setRecipients(Message.RecipientType.CC, cc);
        if (bcc.length > 0) msg.setRecipients(Message.RecipientType.BCC, bcc);

        msg.setSubject(safe(subject));

        MimeMultipart alternative = new MimeMultipart("alternative");
        MimeBodyPart textPart = new MimeBodyPart();
        textPart.setText(stripHtml(htmlBody), "utf-8", "plain");
        alternative.addBodyPart(textPart);
        MimeBodyPart htmlPart = new MimeBodyPart();
        htmlPart.setContent(safe(htmlBody), "text/html; charset=utf-8");
        alternative.addBodyPart(htmlPart);
        msg.setContent(alternative);

        // Envelope sender: only when the identity explicitly carries one. Null (the v1
        // default for every tier) leaves the return-path to SMTP2GO's per-domain VERP.
        if (identity.hasEnvelopeFrom()) {
            session.getProperties().put("mail.smtp.from", identity.envelopeFrom());
        }

        Transport transport = null;
        try {
            transport = session.getTransport("smtp");
            transport.connect();
            transport.sendMessage(msg, msg.getAllRecipients());
        } finally {
            if (transport != null) try { transport.close(); } catch (MessagingException ignore) {}
        }
    }

    /**
     * Identity-aware send from an {@link Email} model (V069): builds the recipient list and
     * body from the model, then sends with the given identity. If {@code identity} is null,
     * delegates to the legacy {@link #sendEmail(Email, EntityManager)} for rollout safety.
     */
    public static void sendEmail(Email email, EmailIdentity identity, EntityManager em) throws MessagingException {
        if (identity == null) {
            sendEmail(email, em); // legacy fallback
            return;
        }
        List<String> toWhoList = new ArrayList<>();
        if (email.getRecipientList() != null) {
            for (Person r : email.getRecipientList()) {
                if (r != null && isValidEmail(r.getEmail())) toWhoList.add(r.getEmail().trim());
            }
        }
        sendEmail(identity, toWhoList, Collections.emptyList(), Collections.emptyList(),
                safe(email.getSubject()), safe(email.getDetail()), em);
    }

    /* ----------------------------- public API (Email model) ----------------------------- */

    public static void sendEmail(Email email, EntityManager em) throws MessagingException {
        System.out.println("E:1");

        // Build TO from the model
        List<String> toWhoList = new ArrayList<>();
        if (email.getRecipientList() != null) {
            for (Person r : email.getRecipientList()) {
                if (r != null && isValidEmail(r.getEmail())) {
                    toWhoList.add(r.getEmail().trim());
                }
            }
        }

        // The email detail already contains the full branded template with attachments
        // (built by EmailTemplate.wrap() in SendEmail25), so just pass it through
        String theMessage = safe(email.getDetail());

        String subject = safe(email.getSubject());

        // FromWho = the human (for Reply-To); real From header will be SMTP_FROM
        String fromWho = (email.getCreatedBy() != null) ? safe(email.getCreatedBy().getEmail()) : "";

        // Optional: wire CC/BCC here if your flow provides it (pass empty for now)
        sendEmail(fromWho, toWhoList, Collections.emptyList(), Collections.emptyList(), subject, theMessage, em);
    }

    /* ----------------------------- Session / settings ----------------------------- */

    private static Session getSession(EntityManager em) throws MessagingException {
        String server   = safe(AppConstantDAO.getConstantValue(em, "SMTP_SERVER"));   // e.g., mail.smtp2go.com
        String port     = safe(AppConstantDAO.getConstantValue(em, "SMTP_PORT"));     // e.g., 587 or 2525
        String user     = safe(AppConstantDAO.getConstantValue(em, "SMTP_USER"));
        String password = safe(AppConstantDAO.getConstantValue(em, "SMTP_PASSWORD"));

        if (server.isBlank() || port.isBlank() || user.isBlank() || password.isBlank()) {
            throw new MessagingException("SMTP settings incomplete (need SMTP_SERVER, SMTP_PORT, SMTP_USER, SMTP_PASSWORD).");
        }

        Properties prop = new Properties();
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true");
        prop.put("mail.smtp.starttls.required", "true");

        prop.put("mail.smtp.host", server);
        prop.put("mail.smtp.port", port);

        // Timeouts – prevent servlet hangs
        prop.put("mail.smtp.connectiontimeout", "10000"); // 10s
        prop.put("mail.smtp.timeout",           "20000"); // 20s
        prop.put("mail.smtp.writetimeout",      "20000"); // 20s

        // Trust server cert by name; SMTP2GO uses valid certs for its hostnames
        prop.put("mail.smtp.ssl.trust", server);

        // Be lenient on address parsing (display names, etc.)
        prop.put("mail.mime.address.strict", "false");

        return Session.getInstance(prop, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(user, password);
            }
        });
    }

    private static String safe(String s) { return s == null ? "" : s; }

    /** Strips HTML tags for plain-text alternative. */
    private static String stripHtml(String html) {
        if (html == null) return "";
        return html
                .replaceAll("<br\\s*/?>", "\n")
                .replaceAll("<p[^>]*>", "\n")
                .replaceAll("</p>", "")
                .replaceAll("<[^>]+>", "")
                .replaceAll("&nbsp;", " ")
                .replaceAll("&amp;", "&")
                .replaceAll("&lt;", "<")
                .replaceAll("&gt;", ">")
                .replaceAll("\\n{3,}", "\n\n")
                .trim();
    }

    /* ----------------------------- legacy helpers (unchanged) ----------------------------- */

    public static Person getPersonByEmail(EntityManager em, String email, PSP psp) {
        if (!isValidEmail(email)) return null;
        Employee employee = getEmployeeByEmail(em, email);
        if (employee != null) {
            Person p = PersonDAO.getPersonByEmployee(em, employee);
            if (p == null) AuthDAO.createPersonFromEmployee(em, employee, psp);
            return PersonDAO.getPersonByEmployee(em, getEmployeeByEmail(em, email));
        }
        Query q = em.createQuery("SELECT p FROM Person p WHERE p.email = :email");
        q.setParameter("email", email);
        List<Person> personList;
        try {
            personList = (List<Person>) q.getResultList();
        } catch (NoResultException e) {
            e.printStackTrace();
            return null;
        }
        if (personList != null && !personList.isEmpty()) return personList.get(0);
        return null;
    }

    public static Employee getEmployeeByEmail(EntityManager em, String email) {
        if (!isValidEmail(email)) return null;
        Query q = em.createQuery("SELECT e FROM Employee e WHERE e.email = :email");
        q.setParameter("email", email);
        List<Employee> employeeList;
        try {
            employeeList = (List<Employee>) q.getResultList();
        } catch (NoResultException e1) {
            return null;
        }
        if (employeeList.isEmpty()) return null;
        return employeeList.get(0);
    }

    public static Employee getEmployeeByEmail(EntityManager em, String email, Person p) {
        if (!isValidEmail(email)) return null;
        Query q = em.createQuery("SELECT e FROM Employee e WHERE e.email = :email");
        q.setParameter("email", email);
        List<Employee> employeeList;
        try {
            employeeList = (List<Employee>) q.getResultList();
        } catch (NoResultException e1) {
            return null;
        }
        if (employeeList.isEmpty()) return null;
        for (Employee ee : employeeList) {
            if (ee.getEmployer().getId() == p.getEmployee().getEmployer().getId())
                return ee;
        }
        return null;
    }

    public static List<Email> getEmailsToRecipient(EntityManager em, String emailAddress) {
        List<Person> personList = getPersonsWithEmail(em, emailAddress);
        List<Email> emailList = new ArrayList<>();
        for (Person p : personList) {
            Query q = em.createQuery("SELECT p FROM Person p WHERE p.id = :id");
            q.setParameter("id", p.getId());
            Person person = (Person) q.getSingleResult();
            List<Email> emails = person.getEmailList();
            if (emails != null && !emails.isEmpty()) {
                emailList.addAll(emails);
            }
        }
        emailList.sort(new EmailComparator());
        return emailList;
    }

    private static List<Person> getPersonsWithEmail(EntityManager em, String emailAddress) {
        Query q = em.createQuery("SELECT p FROM Person p WHERE p.email =:emailAdd");
        q.setParameter("emailAdd", emailAddress);
        List<Person> personList;
        try {
            personList = (List<Person>) q.getResultList();
        } catch (NoResultException e) {
            return Collections.emptyList();
        }
        return personList;
    }

    /* ----------------------------- removed on purpose ----------------------------- */
    // private static Message getMessage() { ... }  // (hardcoded creds) => deleted to prevent accidental use
    // private static Message getMessage(HttpServletRequest request) { ... } // unused; remove to avoid servlet coupling
}