-- =============================================================================
-- schema_version_migration.sql
-- Creates the schema_version table and registers all known migrations.
-- Run this on any database that needs the version history populated
-- (e.g., dev_ssa after DatabaseInitializer, or a manually created schema).
-- The baseline dump already includes this table with data; this script
-- is for cases where the table is empty or missing.
-- =============================================================================

CREATE TABLE IF NOT EXISTS schema_version (
    version VARCHAR(10) NOT NULL,
    description VARCHAR(200),
    script_name VARCHAR(200),
    applied_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (version)
);

-- =============================================================================
-- Record all migrations (per migration_tracker.md)
-- Only insert if not already present
-- =============================================================================

INSERT IGNORE INTO schema_version (version, description, script_name) VALUES
('V001', 'Sales pipeline - tables, columns, entity renames', 'V001__sales_pipeline.sql'),
('V002', 'Sales pipeline 2 - proposal source_activity_id', 'V002__sales_pipeline_2.sql'),
('V003', 'Sales pipeline 3 - LOS expansion, app sections, IRS limits', 'V003__sales_pipeline_3.sql'),
('V004', 'Service manager - enhancement, join tables, SM FKs, LOS columns', 'V004__service_manager.sql'),
('V005', 'Rate manager - ratetable sort_order', 'V005__rate_manager.sql'),
('V006', 'Invitation system - invitation table, agency manager_id', 'V006__invitation_system.sql'),
('V007', 'Resource library - category, material FK, feature FK', 'V007__resource_library.sql'),
('V008', 'Opportunity system - assignee columns, sales tasks', 'V008__opportunity_system.sql'),
('V009', 'Timeclock correction - request table', 'V009__timeclock_correction.sql'),
('V010', 'PSP opportunity integration - sales role and managed_by', 'V010__psp_opportunity_integration.sql'),
('V011', 'BPO delegation - todo BPO columns, todo_guid, is_reverted, task_guid, todo_note table', 'V011__bpo_delegation_feature.sql'),
('V012', 'Role cleanup and PSP branding constants', 'V012__role_cleanup_psp_branding_constants.sql'),
('V013', 'User filter presets - 3 configurable slots per user', 'V013__user_filter_presets.sql'),
('V014', 'Chatbot deployment - note.is_resolution, API key, ticket categories', 'V014__chatbot_deployment.sql'),
('V015', 'Move S3 and API key constants to ssa.properties, delete dead SAVE_PATH', 'V015__constants_to_properties.sql'),
('V016', 'BPO registration and PSP assignment tables', 'V016__bpo_registration_tables.sql'),
('V017', 'Move SYS_HEALTH constants to ssa.properties, add EMAIL_FOOTER_TEXT', 'V017__health_constants_to_properties.sql'),
('V018', 'Application section suppressed column', 'V018__application_section_suppressed.sql'),
('V019', 'Application field suppressed column', 'V019__application_field_suppressed.sql'),
('V020', 'ServiceItem unification - schema additions and data backfill', 'V020__service_item_unification.sql'),
('V021', 'ServiceItem linkage - LOS/Enhancement backfill, Payment Services rename, suppress duplicates', 'V021__service_item_linkage_backfill.sql'),
('V022', 'Orphaned ticket ServiceItem backfill', 'V022__orphaned_ticket_serviceitem_backfill.sql'),
('V023', 'Drop ticketsubcategory table and FK', 'V023__drop_ticketsubcategory.sql'),
('V024', 'Fix views referencing dropped ticket_category column', 'V024__fix_views_drop_ticket_category.sql'),
('V025', 'Add level, los, employer_name to plantype for Summit import', 'V025__plantype_import_columns.sql'),
('V026', 'Benefit table: surrogate auto-increment PK with source tracking', 'V026__benefit_surrogate_pk.sql'),
('V027', 'BPO Registration: task source refactor from Person to BpoRegistration', 'V027__bpo_registration_task_source.sql'),
('V028', 'Benefit plan year start/end columns for renewal date correction', 'V028__benefit_plan_year_columns.sql'),
('V029', 'Add is_active column to user table', 'V029__user_is_active.sql'),
('V030', 'BPO cross-system foundation: psp_clients, delegated_todo, API columns, todo_note GUID', 'V030__bpo_cross_system_foundation.sql'),
('V031', 'ToDoNote cross-system: nullable todo_id/created_by_id, author_name column', 'V031__todo_note_cross_system_nullable.sql'),
('V032', 'Approved vendors registry table', 'V032__approved_vendors_registry.sql'),
('V033', 'ToDoNote attachments: todo_note_id FK on weblink', 'V033__todo_note_attachments.sql'),
('V034', 'Add template_key to applicationsection for starter packages', 'V034__starter_package_template_key.sql'),
('V035', 'Feature headline column and description widening', 'V035__feature_headline_description.sql'),
('V036', 'Proposal section table for composable proposal content', 'V036__proposal_section_table.sql'),
('V037', 'Add LOS/Enhancement scoping to proposal_section', 'V037__proposal_section_scoping.sql'),
('V038', 'Add sort_order to delegated_todo for BPO ordering', 'V038__delegated_todo_sort_order.sql'),
('V039', 'Questionnaire system: templates, fields, instances, values, scoping', 'V039__questionnaire_system.sql'),
('V040', 'Add recurring_series_id to delegated_todo for BPO recurring history', 'V040__delegated_todo_recurring_series.sql'),
('V041', 'Add reviewer tracking fields to application table', 'V041__application_reviewer_fields.sql'),
('V042', 'BPO pending approval workflow - status PENDING support', 'V042__delegated_todo_pending_status.sql'),
('V043', 'Add text_value column to constant for custom landing page HTML', 'V043__custom_landing_page.sql'),
('V044', 'Add agency scoping to proposal_section for TITLE/CLOSING overrides', 'V044__proposal_section_agency_scoping.sql'),
('V045', 'Application selected LOS and Enhancement IDs', 'V045__application_selected_services.sql'),
('V046', 'Chatbot skill table for extensible AI assistant capabilities', 'V046__chatbot_skill_table.sql'),
('V047', 'Composite task order table for cross-sequence ordering', 'V047__composite_task_order.sql'),
('V048', 'Universal import system tables and seed data', 'V048__universal_import_system.sql'),
('V049', 'Add source_task_id to delegated_todo for required-sequence auto-approval', 'V049__delegated_todo_source_task_id.sql'),
('V050', 'BPO default assignee per PSP client', 'V050__bpo_default_assignee.sql'),
('V051', 'Import ID mapping cross-reference table', 'V051__import_id_mapping.sql'),
('V052', 'Import run log cross-reference tracking columns', 'V052__import_run_log_xref_tracking.sql'),
('V053', 'Interactive import enhancements: update mode, mapping status, FK flags', 'V053__interactive_import_enhancements.sql'),
('V054', 'Super User Dashboard — managed_installation table', 'V054__managed_installation.sql'),
('V055', 'Schema info view for structural version identification', 'V055__schema_info_view.sql'),
('V056', 'Training video and single-use token tables', 'V056__training_video_tokens.sql'),
('V057', 'Add suppressed flag to agency table', 'V057__agency_suppressed.sql'),
('V058', 'Add renderer column to questionnaire', 'V058__questionnaire_renderer.sql'),
('V059', 'NDT census-based testing tables', 'V059__ndt_census_tables.sql'),
('V060', 'Outlook add-in user link + weblink.note_id', 'V060__outlook_user_link.sql'),
('V061', 'ToDo-level ownership override for agent delegation', 'V061__todo_ownership_override.sql'),
('V062', 'Per-note agent visibility override', 'V062__note_agent_visibility.sql'),
('V063', 'Knowledge Base tables (knowledge_base, knowledge_chunk, knowledge_chunk_history) + 5 KB registry rows', 'V063__knowledge_base_tables.sql'),
('V064', 'Platform JSON registry seed (proposal_page_builder, automation_email_builder)', 'V064__platform_json_registry_seed.sql'),
('V065', 'Email Draft Assistant skill seed: unique index on chatbot_skill(psp_id,skill_name) + EMAIL_DRAFT_ASSISTANT row', 'V065__email_draft_assistant_skill.sql'),
('V066', 'Per-proposal, per-line agent markup on pricing (proposal_price_adjustment)', 'V066__proposal_price_adjustment.sql'),
('V067', 'Per-agency enable flag for proposal markup (agency.markup_enabled, default OFF)', 'V067__agency_markup_enabled.sql'),
('V068', 'Host-header custom agency landing pages (agency.landing_host unique + landing_html)', 'V068__agency_landing_host.sql'),
('V069', 'Per-agency white-label email sending (agency.email_domain unique + email_verified)', 'V069__agency_email_sending.sql'),
('V070', 'Self-referential agency parent link (GA -> sub-agency hierarchy): agency.parent_agency_id + child index', 'V070__agency_parent.sql'),
('V071', 'Per-agency public quote token (agency.quote_token unique) for RequestQuote sub-agency attribution', 'V071__agency_quote_token.sql'),
('V072', 'Monthly billing run tracking: billing_run + billing_run_step', 'V072__monthly_billing_run_tracking.sql'),
('V073', 'Widen billing_run.current_step to VARCHAR(255)', 'V073__widen_billing_run_current_step.sql'),
('V074', 'Rating-area rate cache for A1 ICHRA illustration', 'V074__rating_area_rate_cache.sql'),
('V075', 'Illustration log for A1 ICHRA rating illustration (no PII)', 'V075__illustration_log.sql'),
('V076', 'County reference data (FIPS, state, name, representative ZIP) -- Texas seed', 'V076__county_reference.sql'),
('V077', 'Per-agency enable flag for ICHRA capability access (agency.ichra_enabled, default OFF)', 'V077__agency_ichra_enabled.sql'),
('V078', 'On-exchange LCSP and benchmark-silver columns for T44 (rating_area_rate_cache.onex_lcsp_premium/onex_benchmark_silver_premium, default NULL)', 'V078__rate_cache_onex_lcsp.sql'),
('V079', 'ICHRA illustration snapshot on a proposal (proposal_ichra_snapshot + proposal_ichra_snapshot_band)', 'V079__proposal_ichra_snapshot.sql'),
('V080', 'ICHRA/QSEHRA Design Advisor: ICHRA_DESIGN_ADVISOR chatbot_skill row + ichra_design knowledge base and chunks', 'V080__ichra_design_advisor_skill.sql'),
('V081', 'Optional opportunity attribution on illustration_log (illustration_log.opportunity_id, nullable, FK to assignee(id))', 'V081__illustration_log_opportunity.sql'),
('V082', 'Make ICHRA_DESIGN_ADVISOR available to non-admin callers (chatbot_skill.is_admin_only 1 -> 0)', 'V082__ichra_design_advisor_non_admin.sql'),
('V083', 'Fix retired model on ICHRA_DESIGN_ADVISOR (chatbot_skill.model -> claude-sonnet-5, max_tokens -> 3072)', 'V083__ichra_design_advisor_model.sql'),
('V084', 'ZIP to county crosswalk table for T74 ZIP intake (zip_county, composite PK, no FK)', 'V084__zip_county_crosswalk.sql'),
('V085', 'Texas ZIP to county crosswalk data (2894 rows, Census 2020 ZCTA relationship file)', 'V085__zip_county_crosswalk_tx.sql'),
('V086', 'Plus-tier classification flag on line of service (los.is_plus_tier, default OFF, no consumer yet)', 'V086__los_plus_tier.sql'),
('V087', 'Plus-tier ZIP/county/headcount intake captured in the Proposal Builder (proposal_ichra_intake, plan_year derived not agent-asserted)', 'V087__proposal_ichra_intake.sql'),
('V088', 'Employer monthly contribution per employee on proposal_ichra_intake (T80 half 1, nullable, no backfill)', 'V088__proposal_ichra_intake_contribution.sql'),
('V089', 'System-managed classification flag on enhancement (enhancement.system_managed, default OFF)', 'V089__enhancement_system_managed.sql'),
('V090', 'ICHRA JSON payload column on proposal_ichra_snapshot (payload_json, MEDIUMTEXT, nullable, no backfill)', 'V090__proposal_ichra_payload.sql'),
('V091', 'ICHRA section selection: enhancement.system_section_key, four selection flags and section 3 comparison inputs on proposal_ichra_intake, band net NOT NULL widened', 'V091__ichra_section_selection.sql'),
('V092', 'HSA Enrollment Assistant: HSA_ENROLLMENT_ASSISTANT chatbot_skill row + 3 ssa_business knowledge_chunk rows (myRSC self-enrollment, [[MYRSC EMPLOYER CODE]] placeholder)', 'V092__hsa_enrollment_assistant.sql'),
('V093', 'Section 125 structure intake inputs on proposal_ichra_intake: monthly_stipend_per_employee and alternative_coverage_monthly_cost (both nullable, no backfill)', 'V093__proposal_ichra_intake_section125.sql'),
('V094', 'Employer participant roster (employer_participant): AMS-owned pre-Summit census keyed to prospect, no name/address uniqueness, no SSN/DOB/compensation columns', 'V094__employer_participant.sql'),
('V095', 'Summit plan template mapping (summit_plan_template_map): PSP-scoped ServiceItem-to-Summit-template map, read ahead of the SUMMIT_PLAN_TEMPLATES property with fallback, created empty, 1:1 enforced by a named unique constraint rather than the PK', 'V095__summit_plan_template_map.sql'),
('V096', 'Summit file export record (summit_file_export): one row per generated Summit export file holding the exact bytes sent, an indexed content SHA-256 for T194 dedupe detection, row/byte counts and the acting user; no transport, no rows inserted', 'V096__summit_file_export.sql'),
('V097', 'Delivery tracking columns on summit_file_export (delivery_status, delivered_at, delivery_dir, delivery_error, all nullable): NULL means download only, PUSHING/PUSHED/PUSH_FAILED track an SFTP push to Summit ImportFiles for T229; no T230 step state', 'V097__summit_file_export_delivery.sql'),
('V098', 'Summit setup step state (summit_setup_step): one row per (proposal_id, step_key) recording PSP-admin Mark done for the T230 phase-1 steps (employer, cdhplan, schedules, demographics), REVIEWED vs MANUAL basis, real FK to summit_file_export on export_id, no response content stored', 'V098__summit_setup_step.sql'),
('V099', 'Audit framework run log (audit_run): one row per (check, run) for T237, counts only (finding_count/status/scrubbed summary+error), no personal data, self-clearing findings, first check ichra_uncoded_participants', 'V099__audit_run.sql'),
('V100', 'Census intake (census_request, census_submission): one-time client upload link with 30-day expiry, parsed whitelisted rows staged for PSP review, raw file never stored (T231 build 1, D45, LA-41)', 'V100__census_intake.sql'),
('V101', 'Summit employer administration flags per elected ServiceItem (summit_service_item_flags): PSP-scoped CDH/COBRA/Retiree/Direct Bill flag mapping, derivation for file 1 (D46), not yet read by any export writer, blocked on SDX-27 (T238 part 1)', 'V101__summit_service_item_flags.sql'),
('V102', 'employer.custom_id: string-faithful CustomID storage from J1 import, set on insert and update, distinct from lossy int er_key (T241/T242)', 'V102__employer_custom_id.sql'),
('V103', 'summit_plan_template_map: seq discriminator + effective_date_rule/offset_months/plan_year_offset_years; unique key widened to (psp, service item, seq) for plan fan-out (W3)', 'V103__plan_template_map_sequence_and_date_rules.sql'),
('V104', 'summit_plan_template_map.is_card_issuer: marks the card-issuer placeholder plan for the $1 seed election export (type=cardseed)', 'V104__plan_template_map_card_issuer.sql'),
('V105', 'summit_plan_template_map enrollment-matrix columns: enrollment_amount_mode (NONE/ANNUAL_ELECTION/MONTHLY_PREMIUM/TIER, default NONE)/affects_payroll/tax_treatment -- amended s52i from an earlier 7-column draft, no consumer yet', 'V105__plan_template_map_enrollment_fields.sql'),
('V106', 'Enrollment matrix storage: matrix/participant/entry tables', 'V106__enrollment_matrix.sql'),
('V107', 'payroll_frequency reference table', 'V107__payroll_frequency.sql');
